{
 "title": "Anomaly detection",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TimeRange",
    "query": {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_alert\")\r\n  |> filter(fn: (r) => r.anomaly_probability >= ${prob_thresh:singlequote})\r\n  |> filter(fn: (r) => contains(value: r.top_contributor_1, set: ${sensor:pipe}))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"contributor_1_zscore\"], desc: true)\r\n  |> limit(n:50)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Sensors with Anomalies",
   "type": "barchart",
   "description": "Sensors that triggered the most anomalies",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Anomaly Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_alert\")\r\n  |> last()\r\n  |> keep(columns: [\"prediction_label\"])\r\n"
    }
   ]
  },
  {
   "title": "Anomaly Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Rate" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_alert\")\r\n  |> filter(fn: (r) => r._field == \"anomaly_probability\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> mean(column: \"_value\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Anomaly Detected in 24 Hours",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Anomalies Last 24 Hrs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: -24d)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_alert\")\r\n  |> filter(fn: (r) => r._field == \"is_anomaly\" and r._value == 1)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> count(column: \"_value\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Detection Methods Used",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_detection\")\r\n  |> filter(fn: (r) => r._field == \"is_anomaly\")\r\n  |> filter(fn: (r) => r._value == 1.0)\r\n  |> group(columns: [\"detection_method\"])\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Latest Anomalies (Top 50)",
   "type": "table",
   "description": "Most recent anomaly detections",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_detection\")\r\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Total Anomalies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_detection\")\r\n  |> filter(fn: (r) => r._field == \"is_anomaly\")\r\n  |> count()\r\n  |> group()\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Critical Anomalies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anomaly_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"anomaly_detection\")\r\n  |> filter(fn: (r) => r._field == \"is_anomaly\")\r\n  |> filter(fn: (r) => r.severity == \"critical\")\r\n  |> count()\r\n  |> group()\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Recall (Attack Detection)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\narray.from(rows: [{_value: 92.07, _time: 2019-07-20T00:00:00Z}])"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "stat",
   "description": "Percentage of alerts that are real attacks",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\narray.from(rows: [{_value: 12.91, _time: 2019-07-20T00:00:00Z}])"
    }
   ]
  }
 ]
}