{
 "title": "NT-SCADA Equipment Monitoring- STAGE 2 - CHEMICAL WATER DOSING",
 "tags": [
  "Industrial",
  "Stage 2 - Chemical Dosing"
 ],
 "time": { "from": "2020-06-22T09:57:21.707Z", "to": "2020-06-22T10:08:22.997Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "DOSING PUMP STATUS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P2_STATE == \"2\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"P202 Status\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "RAW WATER TO DOSAGE FEED TANK",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "RATIO" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: -60)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P2_STATE == \"2\") // only when pump P1 is ON\r\n  |> filter(fn: (r) => r._field == \"FIT 201\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> mean(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "AIT CONDUCTIVITY",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P2_STATE == \"2\") // only when pump P1 is ON\r\n  |> filter(fn: (r) => r._field == \"AIT 201\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> mean(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "RAW WATER TANK VALVE OUTLET",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P2_STATE == \"2\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"MV201\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "ORP LEVEL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P2_STATE == \"2\") // only when pump P1 is ON\r\n  |> filter(fn: (r) => r._field == \"AIT 203\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> mean(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "PHL LEVEL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P2_STATE == \"2\") // only when pump P1 is ON\r\n  |> filter(fn: (r) => r._field == \"AIT 202\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> mean(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  }
 ]
}