{
 "title": "NT-SCADA Equipment Monitoring- STAGE 3 - ULTRAFILTRATION",
 "tags": [
  "Industrial",
  "Stage 3 - Ultrafiltration",
  "Stage 4 - Chloronization"
 ],
 "time": { "from": "2020-06-22T09:57:21.707Z", "to": "2020-06-22T10:08:22.997Z" },
 "refresh": "auto",
 "panels": [
  { "title": "DECHLORANIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAW WATER TANK LEVEL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P4_STATE == \"4\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"LIT 401\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "FEED WATER PUMP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m³/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P4_STATE == \"4\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"P401 Status\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "CHLORINE DESTRUCTION UNIT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P4_STATE == \"4\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"UV401\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "RAW WATER  FEED RATIO",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Rate" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P4_STATE == \"4\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"FIT 401\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "HARDNESS MONITOR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P4_STATE == \"4\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"AIT 401\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "NAHSO DOSING PUMP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P4_STATE == \"4\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"P403 Status\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  { "title": "ULTA FILTRATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "FEED WATER TANK LEVEL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P3_STATE == \"2\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"LIT 301\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "PRESSURE TRANSMITTER",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P3_STATE == \"2\") // only when pump P1 is ON\r\n  |> filter(fn: (r) => r._field == \"DPIT 301\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> mean(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  },
  {
   "title": "BACK WASH VALVE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"normal_data\")\r\n  |> range(start: 0)                       // from the beginning of the bucket\r\n  |> filter(fn: (r) => r._measurement == \"actuator_data\")\r\n  |> filter(fn: (r) => r.P3_STATE == \"2\") // dosing is on\r\n  |> filter(fn: (r) => r._field == \"MV 301\")\r\n  |> keep(columns: [\"_time\", \"_value\"])    // optional, just cleans the output\r\n  |> last(column: \"_value\")                // nulls are ignored by default"
    }
   ]
  }
 ]
}